### ISSUE TITLE
Cannot generate features(features.npy) corresponding to the images in the dataset folder by running: python convfeatures.py 

### ISSUE THREAD

**Issue by Kirthana30** [neural-nuts/image-caption-generator#10]
#Images:
Traceback (most recent call last):
  File "convfeatures.py", line 136, in <module>
    print "#Images:", len(files)
NameError: name 'files' is not defined
I don't know how to fix this error. It is already defined above, so why is it giving me this error? I already downloaded flickr30k_images and results_20130124.token in Dataset folder.

**Comment by CajetanRodrigues** [comment]
how did you solve that ??
