### ISSUE TITLE
Index Error while preparing captions

### ISSUE THREAD

**Issue by jishan900** [neural-nuts/image-caption-generator#13]
Hello all,

When I want to try run this project always show this error :
```
jishan@jishan-HP-ProBook-450-G3:~/Downloads/project$ python main.py --mode train
Required Files not present. Regenerating Data.
Loading Caption Data Dataset/results_20130124.token
Traceback (most recent call last):
File "main.py", line 55, in
config.word_threshold, config.max_len, caption_file, feature_file)
File "/home/jishan/Downloads/project/utils/data_util.py", line 116, in generate_captions
captions = [caps.replace('\n', '').split('\t')[1] for caps in data]
IndexError: list index out of range
```

I already ran `python convfeatures.py` but when I try to run `main.py` then it shows this problem. How can I fix this error? Please help me.

Thanks in advance

**Comment by dust0x** [comment]
Can you share the format of the `results_20130124.token` file you're using? This is what it should look like for Flickr30k
```
1000092795.jpg#0	Two young guys with shaggy hair look at their hands while hanging out in the yard .
1000092795.jpg#1	Two young , White males are outside near many bushes .
1000092795.jpg#2	Two men in green shirts are standing in a yard .
1000092795.jpg#3	A man in a blue shirt standing in a garden .
...
```

**Comment by metalaman** [comment]
This is probably happening because the last line in the _results_20130124.token_ is a _\n_. 
Try replacing the following line 
`captions = [caps.replace('\n', '').split('\t')[1] for caps in data]`
with
`captions = [caps.replace('\n', '').split('\t')[1] for caps in data[:-1]]`

**Comment by dust0x** [comment]
Possible bug status.

**Comment by jishan900** [comment]
thank u @metalaman .already solve the previous issue now tell me how many epoch it will run on train?where is the epoch number defines in the code or number of epochs depends on what?

**Comment by dust0x** [comment]
@jishan900 can you please tell us how you solved the error? Was it using the same fix as suggested by @metalaman. We need to be sure that this was a bug in the data preparation method.

**Comment by dust0x** [comment]
@jishan900 can you please tell us how you solved the error? Was it using the same fix as suggested by @metalaman. We need to be sure that this was a bug in the data preparation method.

As for your second question, all configurations are available in [configuration.py](https://github.com/neural-nuts/image-caption-generator/blob/master/configuration.py#L12). As you will see, `self.nb_epochs` is set to `10000`.

You can refer to [this](https://github.com/neural-nuts/image-caption-generator/issues/11#issuecomment-346983949) conversation for details on best practices for setting `self.nb_epochs`.

**Comment by jishan900** [comment]
yeah that information was helpful and successfully work to train data. Still now training up dataset,if i can find out any other error,then i'll inform u again. :) :+1:
