### ISSUE TITLE
cant run the test mode

### ISSUE THREAD

**Issue by jishan900** [neural-nuts/image-caption-generator#16]
Hello all,

When I want to try run test mode in this project, always show this error :
```
root@jishan-HP-ProBook-450-G3:/home/jishan/Downloads/project# python main.py --mode test
Traceback (most recent call last):
  File "main.py", line 64, in <module>
    if os.path.exists(args.image_path):
  File "/usr/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```
I already ran `python convfeatures.py` and `python main.py --mode train`
but when I try to run `main.py` for test mode then it shows this problem. How can I fix this error? Please help me.

Thanks in advance

**Comment by metalaman** [comment]
Please provide an image path as well with `--image_path VALID_PATH` option

**Comment by jishan900** [comment]
what is VALID_PATH option? Actually i can't understand about this. Please tell me in details. I already take an attempt to run this like this command
root@jishan-HP-ProBook-450-G3:/home/jishan/Downloads/project# python main.py --mode test --image_path ~/Downloads/project/Images/gen_6.png
But output came like this - 
Please provide a valid image path.
 Usage:
 python main.py --mode test --image_path VALID_PATH

**Comment by jishan900** [comment]
problem solve. :) 
Thanks a lot guys...... :+1: :+1: :1st_place_medal:
