### ISSUE TITLE
What are the output node names for freezing the graph ?? I wanted to form .pb frozen graph file..

### ISSUE THREAD

**Issue by piyushhajare** [neural-nuts/image-caption-generator#17]
Want to convert my trained files ( checkpoint , meta file, index file and  data file ) into frozen graph to port that into android. When I'm  executing save_graph.py its asking for correct output node names.

**Comment by pranay360** [comment]
Please provide the following information

1. What are arguments are you passing _save_graph.py_? 
2. Did you make any changes to the encoder/decoder graph? If so, you will need to figure out your own input and output nodes for both encoder and decoder graphs. You can use this code snippet for that-
`print [n.name for n in tf.get_default_graph().as_graph_def().node]`
3. Is it failing for the encoder or for the decoder? If for the decoder, please share the contents of _**DecoderOutput.txt**_ in `model/Decoder/`.

**Comment by piyushhajare** [comment]
1. python save_graph.py --mode encoder --model_folder model/
I actually tried many such combinations of arguments, this is one of them.

2. I tried that code when searching on stackoverflow, when is saw the list of nodes, the output names given are different than those given in save_graph.py

3.  These are the contents of model/Decoder/DecoderOutput.txt
```

LSTM/word_0
LSTM/word_1
LSTM/word_2
LSTM/word_3
LSTM/word_4
LSTM/word_5
LSTM/word_6
LSTM/word_7
LSTM/word_8
LSTM/word_9
LSTM/word_10
LSTM/word_11
LSTM/word_12
LSTM/word_13
LSTM/word_14
LSTM/word_15
LSTM/word_16
LSTM/word_17
LSTM/word_18
LSTM/word_19
LSTM/word_20
LSTM/word_21
```

I have tried many things to just get it worked but it seems that I'm going wrong somewhere.
I request you to please answer complete process step by step (If added in readme it will be beneficial to many).

I appreciate your efforts and work done on this repo.,.Thanks in advance

**Comment by pranay360** [comment]
1. You are using wrong arguments. in the project root directory use - `python utils/save_graph.py --mode encoder --model_folder model/encoder` additionally you may want to use `--read_file 0` if you want to freeze the encoder for the android app.
2. It's not possible unless you made modifications to the code. If you are still facing problems after point#1, then please provide a txt file with the output of the code snippet that I wrote in the previous comment.
3. The contents are correct

I'll update the readme once, this issue gets resolved.

**Comment by piyushhajare** [comment]
This is what I'm getting after running that command 
image-caption-generator-master$ python utils/save_graph.py --mo
de encoder --model_folder model/encoder --read_file 0
```
Traceback (most recent call last):
  File "utils/save_graph.py", line 57, in <module>
    freeze_graph(args.mode, args.read_file, args.model_folder)
  File "utils/save_graph.py", line 10, in freeze_graph
    input_checkpoint = checkpoint.model_checkpoint_path
AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'

```

**Comment by piyushhajare** [comment]
Should I use this command to save encoder ? -

**Comment by pranay360** [comment]
yes, it's necessary to have both encoder and decoder graphs through saveencoder and savedecoder arguments set to 1 while running test. This is a one-time run.

**Comment by piyushhajare** [comment]
Ok I did this process and finally got frozen model. After building app and running it on my mobile it shows some random text words which are not captions.I'll upload its screenshot.
When I added model you provided it's working fine. I have trained model upto 50 epochs and plan to train even more. But still something is going Wrong.

**Comment by pranay360** [comment]
Please open a separate issue. This issue is now fixed, so I am closing it.
