### ISSUE TITLE
When ported to Android random words are generated instead of captions..

### ISSUE THREAD

**Issue by piyushhajare** [neural-nuts/image-caption-generator#19]
When the trained model is frozen and is installed on Android some random arbitrary sequence of words is generated instead of correct captions..
Here is the link to screenshot of output : https://drive.google.com/file/d/1xKc9xgci9yPC1kKpvyprys6lS2GToUeY/view?usp=drivesdk

When project is run on laptop it's working fine.
The model is trained for 50 epochs.
Whereas when the Frozen model provided by author here  https://github.com/neural-nuts/Cam2Caption is used, then captions are generated correctly
i.e "A laptop sitting on the desk"

**Comment by metalaman** [comment]
> When project is run on laptop it's working fine.
Are you generating captions from images from your camera or are you using the provided test dataset.
The quality of captions decreases when you run it on real world.

**Comment by piyushhajare** [comment]
> "A laptop sitting on the desk"
The image shared in link generates this caption, when run on laptop.

**Comment by piyushhajare** [comment]
Can you please tell me how 'idmap' file is generated ?

**Comment by piyushhajare** [comment]
Ok this problem is solved.
I was actually using idmap file provided by author rather than creating my own.Its working now.
Thank you for your help :)
I'm closing this issue..
