### ISSUE TITLE
coco dataset images

### ISSUE THREAD

**Issue by Shanzaay** [neural-nuts/image-caption-generator#31]
For MS coco dataset. which images should i download. MS coco **_2014 Train images [83K/13GB]_**  or  2014 Val images _**[41K/6GB]**_

**Comment by dust0x** [comment]
As the name suggests, the train images are for training your model and the val images are for validation. You can download them as per your requirement, but make sure to point to the correct `--data_path` when executing convfeatures.py.

**Comment by Shanzaay** [comment]
Procedure to Train and Generate Captions: For MSCOCO put
captions_val2014.json and MSCOCO images in COCO-images folder .

I am following the procedure. Thats why i am confused. Because for caption
folder its   *captions_val2014.json*  but for images its not clearly
specified. I am sorry if my question seem ambiguous. I am a beinner so
please deal with it.

**Comment by dust0x** [comment]
I see what you mean, there is some ambiguity in the instructions. But again, the decision is completely up to you. If you're using the training images, it obviously makes sense to use the captions_train2014.json

**Comment by Shanzaay** [comment]
Thanks a bunch Aayush..
