### ISSUE TITLE
Error in convfeatures.py

### ISSUE THREAD

**Issue by CajetanRodrigues** [neural-nuts/image-caption-generator#37]
(cnn) C:\Users\lenovo\Desktop\Image_Captioning\image-caption-generator>python convfeatures.py --data_path Dataset/flickr30k-images --inception_path ConvNets/inception_v4.pb
  File "convfeatures.py", line 55
    print "#Images:", len(files)
                   ^
SyntaxError: invalid syntax

**Comment by dust0x** [comment]
This is Python 2 syntax. What version of Python are you running this with?
