### ISSUE TITLE
features.npy

### ISSUE THREAD

**Issue by namp** [neural-nuts/image-caption-generator#5]
Where can we obtain this file from? It is not included in the Flickr 30K dataset

http://shannon.cs.illinois.edu/DenotationGraph/data/index.html

**Comment by pranay360** [comment]
Sorry, missed it out in the ReadMe
You have to generate features.npy by running convfeatures.py
Usage:
python convfeatures.py

**Comment by namp** [comment]
Indeed. 

Many thanks
