### ISSUE TITLE
can't find Dataset\\features.npy

### ISSUE THREAD

**Issue by kingrain213** [neural-nuts/image-caption-generator#7]
when I run this code for train or test, it both reminds me that ,no file named "Dataset\\features.npy" can be found, could you tell me how can I get the lost file while just for a test? 

I just find "results_20130124.token","inception_v4.pb" these 2 files, could you show or tell me how can I get the other files that I need when test this project.

decoder, encoder, trained_graphs,and so on ,the files in model

 My email is wilson0213@126.com.
 thank you for your reply

**Comment by kingrain213** [comment]
will I have to train a model myself then run test?  I found this file "inception_v4.pb", but the "model" is empty

**Comment by metalaman** [comment]
You need to run convfeatures.py in order to get the features.npy file. This numpy array along with results_20130124.token will be used to generate the vocab.npy, TrainingData.npy  and wtoidx.npy.
Model checkpoints and graphs will be available when you train the model.

**Comment by kingrain213** [comment]
thank you for your introduction， with your help, now I run the training example with 2000 images, thank you very much, I hope I can finish the rest parts :):)

**Comment by autogyro** [comment]
I could not download the flickr30k-images to do the training, who can kindly send to me the  features.npy files? many thanks.
