### ISSUE TITLE
corpus-level bleu & sentence-level bleu

### ISSUE THREAD

**Issue by MenSanYan** [neural-nuts/image-caption-generator#9]
I noticed that two different bleu metrics in your eval.py.
It's thoughtful of you to include both of them.
But, which one is the metrics used in current published papers, such as in <Show, attend and tell- Neural image caption generation with visual attention (2015), K. Xu et al>?
Thanks for your answers.

**Comment by metalaman** [comment]
Show, Attend and Tell uses [this](https://github.com/tylin/coco-caption) and so does Show and Tell. Not sure if their implementation computes the micro-average precision(corpus-level) or the macro(sentence-level).

**Comment by MenSanYan** [comment]
@metalaman thanks, I will try [https://github.com/tylin/coco-caption](url).
